### ISSUE TITLE
Log all important user actions

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#411]
* [ ] find out if we can log VSCode events when user uses "navigate to file" (CTRL+P), or "find files" or clicks into the "Outline" window etc?

* [x] if not, use code navigation events to capture when a user moves the cursor to some line/function/file

**Comment by MiccWan** [comment]
The VSCode `onCommand` API was once been done but been removed soon after, check [this comment](https://github.com/microsoft/vscode/issues/78091#issuecomment-521640092)
We have to trace user cursor location manually in order to analyze the debug progress
- [ ] In pdp, check `UserActionType.EditorEvent`, if user has navigated to a new `staticContext`, create a new step
  - [ ] To apply the changes to logs from first experiment, need to add version check in `pdp.load`
    - if `version === 1`, avoid adding `actionGroups`, `steps` and add `userAction` by `pdp.addNewUserAction`
    - otherwise just use the origin parse method
